//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EletronicShippingSuplies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID { get; set; }
        public int OWNER { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string POSTALCODE { get; set; }
        public string NUMBER { get; set; }
        public bool ISDEFAULT { get; set; }
    
        public virtual User User { get; set; }
    }
}
