//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EletronicShippingSuplies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int OWNER { get; set; }
        public decimal PRICE { get; set; }
        public System.DateTime DATE { get; set; }
        public string STATE { get; set; }
        public int QUANTITY { get; set; }
        public int CARTID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
